version: '3'

dotenv:
  - sandau_cvat.env
env:
  CVAT_VERSION: v2.23.0
  ACME_EMAIL: matt@sandau.dev

tasks:
  build:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml build

  run:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.https.yml up -d

  run-serverless-dev:
    cmds:
      - docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --force-recreate

  run-serverless:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.https.yml -f components/serverless/docker-compose.serverless.yml up -d

  stop:
    cmds:
      - docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml down

  deploy-sam:
    cmds:
      - cd serverless && ./deploy_gpu.sh pytorch/facebookresearch/segment_anything_2/nuclio/

  deploy-yolo:
    cmds:
      - cd serverless && ./deploy_gpu.sh pytorch/ultralytics/yolov8/nuclio/

  deploy-siammask:
    cmds:
      - cd serverless && ./deploy_gpu.sh pytorch/foolwood/siammask/nuclio/

  logs:
    cmds:
      - docker compose logs -f

  # dotenv files can be found on Azure - configuration-resources container
  run-serverless-prod:
    cmds:
      # NOTE: running this as `task run...` vs `task: run...` handles enviroment variables as expected
      - |
        if ! command -v nuctl &> /dev/null; then
          echo "nuctl not found, installing...";
          curl -s https://api.github.com/repos/nuclio/nuclio/releases/latest \
            | grep -i "browser_download_url.*nuctl.*$(uname)" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -O nuctl -qi - && chmod +x nuctl
          sudo mv nuctl /usr/local/bin/nuctl
        fi
      - task run-serverless
      - task: deploy-sam
      - task: deploy-yolo

# dotenv files can be found on Azure - configuration-resources container
  run-local-dev:
    cmds:
      # NOTE: running this as `task run...` vs `task: run...` handles enviroment variables as expected
      - task run-serverless-dev